#############################################################################
# Makefile for building: CS470_HW.app/Contents/MacOS/CS470_HW
# Generated by qmake (3.1) (Qt 5.12.4)
# Project:  CS470.pro
# Template: app
# Command: /Users/bravo/Qt5.12.4/5.12.4/clang_64/bin/qmake -o CS470_HW.xcodeproj/project.pbxproj CS470.pro -spec macx-xcode
#############################################################################

MAKEFILE      = project.pbxproj

EQ            = =

QMAKE    = /Users/bravo/Qt5.12.4/5.12.4/clang_64/bin/qmake
CS470_HW.xcodeproj/project.pbxproj: CS470.pro /Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/macx-clang/qmake.conf /Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/spec_pre.prf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/qdevice.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/device_config.prf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/common/unix.conf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/common/mac.conf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/common/macx.conf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/common/sanitize.conf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/common/gcc-base.conf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/common/clang.conf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/common/clang-mac.conf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/qconfig.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/qt_functions.prf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/qt_config.prf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/macx-xcode/qmake.conf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/toolchain.prf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/mac/toolchain.prf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/default_pre.prf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/mac/default_pre.prf \
		CS470_common.pro \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/resolve_config.prf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/default_post.prf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/qt.prf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/resources.prf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/moc.prf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/uic.prf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/unix/thread.prf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/mac/mac.prf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/warn_on.prf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/qmake_use.prf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/file_copies.prf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/mac/rez.prf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/exceptions.prf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/yacc.prf \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/lex.prf \
		CS470.pro \
		CS470.qrc \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/lib/QtPrintSupport.framework/QtPrintSupport.prl \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/bravo/Qt5.12.4/5.12.4/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o CS470_HW.xcodeproj/project.pbxproj CS470.pro -spec macx-xcode
	@echo 'warning: Xcode project has been regenerated, custom settings have been lost. Use CONFIG+=no_autoqmake to prevent this behavior in the future, at the cost of requiring manual project change tracking.'
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/spec_pre.prf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/qdevice.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/device_config.prf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/common/unix.conf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/common/mac.conf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/common/macx.conf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/common/sanitize.conf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/common/gcc-base.conf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/common/gcc-base-mac.conf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/common/clang.conf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/common/clang-mac.conf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/qconfig.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_core.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_help.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_location.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_network.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_repparser.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_scxml.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/qt_functions.prf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/qt_config.prf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/macx-clang/qmake.conf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/macx-xcode/qmake.conf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/exclusive_builds.prf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/mac/sdk.prf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/toolchain.prf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/mac/toolchain.prf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/default_pre.prf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/mac/default_pre.prf:
CS470_common.pro:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/resolve_config.prf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/default_post.prf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/mac/default_post.prf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/mac/objective_c.prf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/qt.prf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/resources.prf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/moc.prf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/unix/opengl.prf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/uic.prf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/unix/thread.prf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/mac/mac.prf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/warn_on.prf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/qmake_use.prf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/file_copies.prf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/mac/rez.prf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/mac/asset_catalogs.prf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/testcase_targets.prf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/exceptions.prf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/yacc.prf:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/mkspecs/features/lex.prf:
CS470.pro:
CS470.qrc:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/lib/QtPrintSupport.framework/QtPrintSupport.prl:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/bravo/Qt5.12.4/5.12.4/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o CS470_HW.xcodeproj/project.pbxproj CS470.pro -spec macx-xcode

qmake_all: FORCE

